export const Monday = [
    {id:1, hour:'7 - 8', assignatureName:" "},
    {id:2, hour:'8 - 9', assignatureName:" "},
    {id:3, hour:'9 - 10', assignatureName:" "},
    {id:4, hour:'10 - 11', assignatureName:" "},
    {id:5, hour:'11 - 12', assignatureName:" "},
    {id:6, hour:'12 - 13', assignatureName:" "},
    {id:7, hour:'13 - 14', assignatureName:" "},
    {id:8, hour:'14 - 15', assignatureName:" "},
    {id:9, hour:'15 - 16', assignatureName:" "},
    {id:10, hour:'16 - 17', assignatureName:" "},
    {id:11, hour:'17 - 18', assignatureName:" "},
    {id:12, hour:'18 - 19', assignatureName:" "},
    {id:13, hour:'19 - 20', assignatureName:" "},
    {id:14, hour:'20 - 21', assignatureName:" "},
    {id:15, hour:'21 - 22', assignatureName:" "},
]

export const Tuesday = [
    {id:16, hour:'7 - 8', assignatureName:" "},
    {id:17, hour:'8 - 9', assignatureName:" "},
    {id:18, hour:'9 - 10', assignatureName:" "},
    {id:19, hour:'10 - 11', assignatureName:" "},
    {id:20, hour:'11 - 12', assignatureName:" "},
    {id:21, hour:'12 - 13', assignatureName:" "},
    {id:22, hour:'13 - 14', assignatureName:" "},
    {id:23, hour:'14 - 15', assignatureName:" "},
    {id:24, hour:'15 - 16', assignatureName:" "},
    {id:25, hour:'16 - 17', assignatureName:" "},
    {id:26, hour:'17 - 18', assignatureName:" "},
    {id:27, hour:'18 - 19', assignatureName:" "},
    {id:28, hour:'19 - 20', assignatureName:" "},
    {id:29, hour:'20 - 21', assignatureName:" "},
    {id:30, hour:'21 - 22', assignatureName:" "},
]

export const Wednesday = [
    {id:31, hour:'7 - 8', assignatureName:" "},
    {id:32, hour:'8 - 9', assignatureName:" "},
    {id:33, hour:'9 - 10', assignatureName:" "},
    {id:34, hour:'10 - 11', assignatureName:" "},
    {id:35, hour:'11 - 12', assignatureName:" "},
    {id:36, hour:'12 - 13', assignatureName:" "},
    {id:37, hour:'13 - 14', assignatureName:" "},
    {id:38, hour:'14 - 15', assignatureName:" "},
    {id:39, hour:'15 - 16', assignatureName:" "},
    {id:40, hour:'16 - 17', assignatureName:" "},
    {id:41, hour:'17 - 18', assignatureName:" "},
    {id:42, hour:'18 - 19', assignatureName:" "},
    {id:43, hour:'19 - 20', assignatureName:" "},
    {id:44, hour:'20 - 21', assignatureName:" "},
    {id:45, hour:'21 - 22', assignatureName:" "},
]

export const Thursday = [
    {id:46, hour:'7 - 8', assignatureName:" "},
    {id:47, hour:'8 - 9', assignatureName:" "},
    {id:48, hour:'9 - 10', assignatureName:" "},
    {id:49, hour:'10 - 11', assignatureName:" "},
    {id:50, hour:'11 - 12', assignatureName:" "},
    {id:51, hour:'12 - 13', assignatureName:" "},
    {id:52, hour:'13 - 14', assignatureName:" "},
    {id:53, hour:'14 - 15', assignatureName:" "},
    {id:54, hour:'15 - 16', assignatureName:" "},
    {id:55, hour:'16 - 17', assignatureName:" "},
    {id:56, hour:'17 - 18', assignatureName:" "},
    {id:57, hour:'18 - 19', assignatureName:" "},
    {id:58, hour:'19 - 20', assignatureName:" "},
    {id:59, hour:'20 - 21', assignatureName:" "},
    {id:60, hour:'21 - 22', assignatureName:" "},
]

export const Friday = [
    {id:61, hour:'7 - 8', assignatureName:" "},
    {id:62, hour:'8 - 9', assignatureName:" "},
    {id:63, hour:'9 - 10', assignatureName:" "},
    {id:64, hour:'10 - 11', assignatureName:" "},
    {id:65, hour:'11 - 12', assignatureName:" "},
    {id:66, hour:'12 - 13', assignatureName:" "},
    {id:67, hour:'13 - 14', assignatureName:" "},
    {id:68, hour:'14 - 15', assignatureName:" "},
    {id:69, hour:'15 - 16', assignatureName:" "},
    {id:70, hour:'16 - 17', assignatureName:" "},
    {id:71, hour:'17 - 18', assignatureName:" "},
    {id:72, hour:'18 - 19', assignatureName:" "},
    {id:73, hour:'19 - 20', assignatureName:" "},
    {id:74, hour:'20 - 21', assignatureName:" "},
    {id:75, hour:'21 - 22', assignatureName:" "},
]

export const Saturday = [
    {id:76, hour:'7 - 8', assignatureName:" "},
    {id:77, hour:'8 - 9', assignatureName:" "},
    {id:78, hour:'9 - 10', assignatureName:" "},
    {id:79, hour:'10 - 11', assignatureName:" "},
    {id:80, hour:'11 - 12', assignatureName:" "},
    {id:81, hour:'12 - 13', assignatureName:" "},
    {id:82, hour:'13 - 14', assignatureName:" "},
    {id:83, hour:'14 - 15', assignatureName:" "},
    {id:84, hour:'15 - 16', assignatureName:" "},
    {id:85, hour:'16 - 17', assignatureName:" "},
    {id:86, hour:'17 - 18', assignatureName:" "},
    {id:87, hour:'18 - 19', assignatureName:" "},
    {id:88, hour:'19 - 20', assignatureName:" "},
    {id:89, hour:'20 - 21', assignatureName:" "},
    {id:90, hour:'21 - 22', assignatureName:" "},
]

export const Assignatures = [
    {assignatureName: 'Calculo diferencial',         semester: '1',},
    {assignatureName: 'Matematicas discretas',       semester: '1',},
    {assignatureName: 'Quimica',                     semester: '1',},
    {assignatureName: 'Fundamentos de programación', semester: '1',},
    {assignatureName: 'POO',                         semester: '1',},
    {assignatureName: 'Taller de investigacion',     semester: '1',},
    {assignatureName: 'Formación cívica y ética',    semester: '1',},
  ];